### ISSUE TITLE
NOT WORKING NO MATTER WHAT I DO

### ISSUE THREAD

**Issue by Xyrn23** [jordienr/whatamesh#6]
> so when I try to use this with html, `css` and `js` it doesn't work. here's my setup:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
    <script type="module" src="Gradient.mjs">
        import { Gradient } from './Gradient.sjs'
        const gradient = new Gradient()
        gradient.initGradient('#gradient-canvas')
    </script>
  </head>
  <body>
    <canvas id="gradient-canvas" data-transition-in > </canvas>
  </body>
</html>
```

```css
#gradient-canvas {
    width: 100%;
    height: 100%;
    --gradient-color-1: #449ce4;
    --gradient-color-2: #2f8bc1;
    --gradient-color-3: #ccbeee;
    --gradient-color-4: #4c57f6;
  }
```

and the Gradient js is [here](https://raw.githubusercontent.com/jordienr/whatamesh/master/lib/Gradient.js)
even I put the script part on the body I still see nothing on the screen only a blank white page. also even I only use `.js` file exentension nothing happens when I look up on the console still nothing dunno why

![image](https://github.com/jordienr/whatamesh/assets/93040266/ea4864c8-e79b-4049-b319-49408a8d7ef6)
